services:
  app:
    image: stef500/kroki-flask-generator:latest
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - KROKI_URL=http://kroki:8000
      - FLASK_CONFIG=production
      - REQUEST_TIMEOUT=15
      - MAX_BYTES=2000000
    depends_on:
      kroki:
        condition: service_healthy
    networks:
      - kroki-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  kroki:
    image: yuzutech/kroki:latest
    expose:
      - "8000"
    environment:
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_MERMAID_PORT=8002
      - KROKI_EXCALIDRAW_HOST=excalidraw
      - KROKI_EXCALIDRAW_PORT=8004
    depends_on:
      mermaid:
        condition: service_started
      excalidraw:
        condition: service_started
    networks:
      - kroki-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  mermaid:
    image: yuzutech/kroki-mermaid:latest
    expose:
      - "8002"
    networks:
      - kroki-network
    restart: unless-stopped
    environment:
      - PUPPETEER_ARGS=--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage

  excalidraw:
    image: yuzutech/kroki-excalidraw:latest
    expose:
      - "8004"
    networks:
      - kroki-network
    restart: unless-stopped

networks:
  kroki-network:
    driver: bridge